name: state_composer
version: 0.0.0
description: Create state machines with object composition 
homepage: https://github.com/FelipeMarra/state-composer

environment:
    sdk: ">=2.16.1 <3.0.0"

dependencies:


dev_dependencies:
