name: state_composer
version: 0.0.0
description: Create ComposerState machines with object composition 
homepage: https://github.com/FelipeMarra/state_composer

environment:
    sdk: ">=2.16.1 <3.0.0"

dependencies:


dev_dependencies: 
    test: ^1.20.1
